import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { ToastContainer } from "react-toastify";
import ReduxProvider from "@/redux/redux-provider";
import "react-toastify/dist/ReactToastify.css";

// Define custom fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the app
export const metadata = {
  title: "Website",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Toast notifications */}
        <ToastContainer position="top-right" autoClose={3000} />

        {/* Redux provider wrapping the app */}
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}